### ISSUE TITLE
Support for kernel 3.7

### ISSUE THREAD

**Issue by alexxy** [shinpei0208/gdev#13]
Is there any work to support kernel 3.7. Also is there soe plans to merge kernel modules into mainline kernel?

**Comment by shinpei0208** [comment]
3.7 will be supported soon. Nouveau prefers user-space runtime. Hence the answer would be NO at the moment. That's why I made user/lib/nouveau - let's hope someday Nouveau will accept in-kernel runtime...

**Comment by alexxy** [comment]
ghm... what i need to run gdev with nouveau? do i need patched kernel and gdev kernel modules? Also what do i need to run cuda apps?

**Comment by shinpei0208** [comment]
Gdev has two types of runtime:  user-space and in-kernel. The in-kernel requires a patched kernel and the Gdev kernel module, while the user-space runtime doesn't need a patched kernel and the Gdev kernel module at all.
Please follow the instruction in README. In particular, if you don't want to use the in-kernel runtime, just skip Step 3 and 4. To run CUDA apps, you just need to install CUDA runtime provided by Gdev. README tells you how to install it.

**Comment by shinpei0208** [comment]
Done.
