### ISSUE TITLE
How to developing manage memory in GPU?

### ISSUE THREAD

**Issue by rchatsiri** [shinpei0208/gdev#2]
Hello All
     I have plan for improving DRM and API managed  memory of GPU. Gdev will be help for manage memory for my algorithms search binary file.  I  research in fast search string algorithm with GPU topic. My question about for start to hacking/developing DRM and Gdev API.

```
 1)     Is Gdev is open source project license?
 2)     How should I  starting or learning the DRM for hack or develop API of Gdev? I should do only developing Gdev API for managing memory in GPU, right?
```

Sorry, If I write in issues topic. I cannot found another place for posting.

Thank you
Chatsiri Rattana.

**Comment by shinpei0208** [comment]
Gdev is a resource management abstraction built on top of DRM. You can use Gdev instead of DRM for your memory management scheme. However though you may need DRM if very low level memory management is required.

Shinpei

**Comment by rchatsiri** [comment]
Gdev, It is an open source license, right?

**Comment by shinpei0208** [comment]
Yes.
