### ISSUE TITLE
Using cuda in scheduler

### ISSUE THREAD

**Issue by amritoit** [shinpei0208/gdev#21]
Hi, I want to use cuda in the linux scheduler ? can I use cuda in current CFS , 

Pl let me know?

**Comment by shinpei0208** [comment]
CFS is just a Linux scheduler. It doesn't matter if you use GPUs or not. So yes :)

**Comment by amritoit** [comment]
Hi,

Ok thanks for your quick reply. I want to know one more thing . Is it
possible to use cuda in the kernel space without using nvrm driver? I am
right now using nouveau but cuda context is not being created.

On Sat, Mar 29, 2014 at 6:42 PM, Shinpei Kato notifications@github.comwrote:

> CFS is just a Linux scheduler. It doesn't matter if you use GPUs or not.
> So yes :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shinpei0208/gdev/issues/21#issuecomment-38995196
> .

## 

Thanks & Regards,
Amritendu Mondal | IIT Madras
(c) : +91 9043812198

Google plus https://plus.google.com/u/0/110701489330421342118/posts/p/pub
Facebook https://www.facebook.com/amritoit
Linkedinhttp://www.linkedin.com/profile/view?id=110466422&trk=tab_pro
