### ISSUE TITLE
error with command: git clone git://0x04.net/envytools.git

### ISSUE THREAD

**Issue by HATEM-ELAZAB** [shinpei0208/gdev#26]
when ever i try to execute the command:
git clone git://0x04.net/envytools.git

i recieve the following error message :
Cloning into 'envytools'...
fatal: remote error: access denied or repository not exported: /envytools.git

**Comment by mwkmwkmwk** [comment]
The envytools repo has been moved to github. I have updated the README correspondingly.

**Comment by shinpei0208** [comment]
Marcin,

Thanks a lot for your quick action :)

Shinpei
