### ISSUE TITLE
The supported Nvdia cards.

### ISSUE THREAD

**Issue by himeshsameera** [shinpei0208/gdev#29]
I installed the user mode api and cuda module for a student project using gdev. But when running the test programs a message apeared 
" [gdev] NV98 not supported. "
with a segmentation fault. 
My GPU is NVIDIA Corporation G98 [GeForce 8400 GS Rev. 2] as shown in lspci.

Does gdev really doesnot support G98 or is this some other message?
If it does not support G98 can you please come up with a list of supported Nvdia devices. It will be a great help for new users.

**Comment by shinpei0208** [comment]
Unfortunately NV98 is not supported by Gdev. In fact, only Fermi and Kepler GPUs are supported at this moment. I have added the list of tested GPUs here:
https://github.com/shinpei0208/gdev/wiki/List-of-tested-GPUs

**Comment by himeshsameera** [comment]
Thanks for the list. I'll try it with a newer GPU.
